<?php

[
    ':authority' => 'www.instagram.com',
    ':method' => 'GET',
    ':path' => '/api/v1/direct_v2/has_interop_upgraded/',
    ':scheme' => 'https',
    'accept' => '*/*',
    'accept-encoding' => 'gzip, deflate, br, zstd',
    'accept-language' => 'en-US,en;q=0.9',
    'dpr' => '1',
    'priority' => 'u=1, i',
    'referer' => 'https://www.instagram.com/accounts/onetap/?next=%2F',
    'sec-ch-prefers-color-scheme' => 'dark',
    'sec-ch-ua' => '"Chromium";v="124", "Google Chrome";v="124", "Not-A.Brand";v="99"',
    'sec-ch-ua-full-version-list' => '"Chromium";v="124.0.6367.60", "Google Chrome";v="124.0.6367.60", "Not-A.Brand";v="99.0.0.0"',
    'sec-ch-ua-mobile' => '?0',
    'sec-ch-ua-model' => '""',
    'sec-ch-ua-platform' => '"Windows"',
    'sec-ch-ua-platform-version' => '"10.0.0"',
    'sec-fetch-dest' => 'empty',
    'sec-fetch-mode' => 'cors',
    'sec-fetch-site' => 'same-origin',
    'user-agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
    'x-asbd-id' => '129477',
    'x-csrftoken' => '18tBKbXgZKFO7y2lxfpRCGs3WoBQsOxz',
    'x-ig-app-id' => '936619743392459',
    'x-ig-www-claim' => 'hmac.AR0k20fADFzRHHFdazSdGtL0iZMIGdPfXsqtL0s88sQVSjgS',
    'x-requested-with' => 'XMLHttpRequest'
];
