<?php
array(
    ':authority' => 'www.instagram.com',
    ':method' => 'GET',
    ':path' => '/atifaslam',
    ':scheme' => 'https',
    'accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'accept-encoding' => 'gzip, deflate, br, zstd',
    'accept-language' => 'en-US,en;q=0.9',
    'dpr' => '1',
    'priority' => 'u=0, i',
    'sec-ch-prefers-color-scheme' => 'dark',
    'sec-ch-ua' => '"Chromium";v="124", "Google Chrome";v="124", "Not-A.Brand";v="99"',
    'sec-ch-ua-full-version-list' => '"Chromium";v="124.0.6367.60", "Google Chrome";v="124.0.6367.60", "Not-A.Brand";v="99.0.0.0"',
    'sec-ch-ua-mobile' => '?0',
    'sec-ch-ua-model' => '""',
    'sec-ch-ua-platform' => '"Windows"',
    'sec-ch-ua-platform-version' => '"10.0.0"',
    'sec-fetch-dest' => 'document',
    'sec-fetch-mode' => 'navigate',
    'sec-fetch-site' => 'none',
    'sec-fetch-user' => '?1',
    'upgrade-insecure-requests' => '1',
    'user-agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
    'viewport-width' => '960',
);
